version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  server:
    build: ./server
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/hrms
      - JWT_SECRET=change_this_in_production
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    ports:
      - "5000:5000"
volumes:
  mongo-data:
